x-base: &base
  image: crisp_controllers_demos:base
  build:
    context: .
    args:
      ROS_DISTRO: humble
    target: base

  network_mode: host
  ipc: host
  pid: host
  privileged: true

  command: /bin/bash
  tty: true
  stdin_open: true

  volumes:
    - $HOME/.Xauthority:/root/.Xauthority
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /dev:/dev
    - ./limits.conf:/etc/security/limits.conf
    - $HOME/.ssh:/home/ros/.ssh

  environment:
    QT_X11_NO_MITSHM: 1
    DISPLAY: ${DISPLAY}
    ROS_DOMAIN_ID: 100
    RCUTILS_COLORIZED_OUTPUT: 1
    SHELL: /bin/bash
    FASTDDS_BUILTIN_TRANSPORTS: UDPv4

  cap_add:
    - SYS_NICE

  ulimits:
    rtprio: 99
    rttime: -1
    memlock: 8428281856

x-franka-overlay: &franka-overlay
  <<: *base
  image: crisp_controllers_demos:franka-overlay
  build:
    context: .
    target: franka-overlay

# ---------- Services ----------
services:
  devcontainer:
    <<: *base

  franka-overlay:
    <<: *franka-overlay

  launch_franka:
    <<: *franka-overlay
    command: >
      bash -lc "source /opt/ros/humble/setup.bash &&
      source install/setup.bash &&
      ros2 launch crisp_controllers_robot_demos franka.launch.py
      arm_id:=fr3 use_fake_hardware:=${FRANKA_FAKE_HARDWARE} robot_ip:=${ROBOT_IP} use_rviz:=True"

  launch_dual_franka:
    <<: *franka-overlay
    command: >
      bash -lc "source /opt/ros/humble/setup.bash &&
      source install/setup.bash &&
      ros2 launch crisp_controllers_robot_demos dual_franka.launch.py
      use_fake_hardware:=${FRANKA_FAKE_HARDWARE}
      left_robot_ip:=${LEFT_ROBOT_IP} right_robot_ip:=${RIGHT_ROBOT_IP}"

  launch_franka_zenoh:
    <<: *franka-overlay
    command: >
      bash -lc "source /opt/ros/humble/setup.bash &&
      source install/setup.bash &&
      source src/crisp_controllers_demos/scripts/set_zenoh_config.sh &&
      source src/crisp_controllers_demos/scripts/start_router.sh &&
      ros2 launch crisp_controllers_robot_demos franka.launch.py
      arm_id:=fr3 use_fake_hardware:=${FRANKA_FAKE_HARDWARE} robot_ip:=${ROBOT_IP} use_rviz:=True"

  launch_franka_cyclone:
    <<: *franka-overlay
    command: >
      bash -lc "source /opt/ros/humble/setup.bash &&
      source install/setup.bash &&
      source src/crisp_controllers_demos/scripts/set_cyclone_config.sh &&
      ros2 launch crisp_controllers_robot_demos franka.launch.py
      arm_id:=fr3 use_fake_hardware:=${FRANKA_FAKE_HARDWARE} robot_ip:=${ROBOT_IP} use_rviz:=True"

  launch_dual_franka_zenoh:
    <<: *franka-overlay
    command: >
      bash -lc "source /opt/ros/humble/setup.bash &&
      source install/setup.bash &&
      source src/crisp_controllers_demos/scripts/set_zenoh_config.sh &&
      ros2 pkg xml rmw_zenoh_cpp &&
      RUST_LOG=zenoh=severe ros2 launch crisp_controllers_robot_demos dual_franka.launch.py
      use_fake_hardware:=${FRANKA_FAKE_HARDWARE}
      left_robot_ip:=${LEFT_ROBOT_IP} right_robot_ip:=${RIGHT_ROBOT_IP}"

  launch_dual_franka_cyclone:
    <<: *franka-overlay
    command: >
      bash -lc "source /opt/ros/humble/setup.bash &&
      source install/setup.bash &&
      source src/crisp_controllers_demos/scripts/set_cyclone_config.sh &&
      ros2 launch crisp_controllers_robot_demos dual_franka.launch.py
      use_fake_hardware:=${FRANKA_FAKE_HARDWARE}
      left_robot_ip:=${LEFT_ROBOT_IP} right_robot_ip:=${RIGHT_ROBOT_IP}"

  launch_zenoh_router:
    <<: *base
    command: >
      bash -lc "source /opt/ros/humble/setup.bash &&
      export ROS_DOMAIN_ID=100 &&
      export RMW_IMPLEMENTATION=rmw_zenoh_cpp &&
      export RUST_LOG=zenoh=info &&
      ros2 daemon stop && ros2 daemon start &&
      ros2 run rmw_zenoh_cpp rmw_zenohd"

